# Generated by Django 3.1.4 on 2020-12-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='name',
            new_name='user',
        ),
    ]
